// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/TeslaMode1X/PVH_order/internal/api"
	"github.com/TeslaMode1X/PVH_order/internal/config"
	"github.com/TeslaMode1X/PVH_order/internal/db"
	"github.com/TeslaMode1X/PVH_order/internal/domain/providers/auth"
	"github.com/TeslaMode1X/PVH_order/internal/domain/providers/materials"
	"github.com/TeslaMode1X/PVH_order/internal/domain/providers/systems"
	"github.com/TeslaMode1X/PVH_order/internal/domain/providers/user"
	"log/slog"
)

// Injectors from wire.go:

func InitializeAPI(cfg *config.Config, log *slog.Logger) (*api.ServerHTTP, error) {
	sqlDB, err := db.ConnectToDB(cfg)
	if err != nil {
		return nil, err
	}
	repository := auth.ProvideAuthRepository(sqlDB)
	userRepository := user.ProvideUserRepository(sqlDB)
	service := auth.ProvideAuthService(repository, userRepository)
	handler := auth.ProvideAuthHandler(service, log)
	userService := user.ProvideUserService(userRepository)
	userHandler := user.ProvideUserHandler(userService, log)
	materialsRepository := materials.ProvideMaterialRepository(sqlDB)
	materialsService := materials.ProvideMaterialService(materialsRepository)
	materialsHandler := materials.ProvideMaterialHandler(materialsService, log)
	systemsRepository := systems.ProvideSystemsRepository(sqlDB)
	systemsService := systems.ProvideSystemsService(systemsRepository, materialsRepository)
	systemsHandler := systems.ProvideSystemsHandler(systemsService, log)
	serverHTTP := api.NewServerHTTP(cfg, handler, userHandler, materialsHandler, systemsHandler)
	return serverHTTP, nil
}
