services:
  db:
    container_name: pvh_postgres_db
    restart: always
    image: postgres:17
    env_file:
      - .env
#    expose:
#      - "5432"
#    Testing purposes(to open db in console)
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network
  migrate:
    image: migrate/migrate
    volumes:
      - ./cmd/migrator/migrations:/migrations
    env_file:
      - ./.env
    command:
      [ "-source", "file://migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  server:
    container_name: pvh_server
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: pvh_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge